const SITE_CONFIG = {
  telegramBaseUrl: "https://t.me/",
  telegramStarts: {
    general: "",
    candidate: "?start=candidate",
    company: "?start=company",
    show: "?start=boss_show",
  },
  email: "hello@bosshiring.com",
  socialLinks: {
    facebook: "https://www.facebook.com/",
    tiktok: "https://www.tiktok.com/",
    telegram: "https://t.me/",
    youtube: "https://www.youtube.com/",
    instagram: "https://www.instagram.com/",
  },
  adminUrl: "#",
};

const I18N = {
  zh: {
    "brand.subtitle": "柬埔寨招聘服务",
    "nav.home": "首页",
    "nav.services": "服务",
    "nav.employers": "企业招聘",
    "nav.candidates": "求职者服务",
    "nav.team": "关于我们",
    "nav.interviews": "往期访谈",
    "nav.contact": "联系我们",
    "nav.cta": "Telegram 咨询",
    "nav.show": "Boss来了",
    "hero.eyebrow": "柬埔寨领先的人才招聘与企业服务平台",
    "hero.title": "Boss来了，让企业被看见",
    "hero.copy": "AI驱动的人才招聘与企业服务平台，连接企业招聘、人才筛选与品牌曝光。",
    "hero.showCta": "申请企业采访",
    "hero.companyCta": "发布招聘需求",
    "hero.candidateCta": "求职者登记资料",
    "hero.featureBadge": "Boss来了",
    "hero.featureTitle": "深入企业一线，发现真实的成长故事",
    "hero.featureCopy": "对话企业家，了解行业、发现机会，让求职者更了解企业，也让企业建立雇主信任。",
    "hero.tab1": "企业访谈",
    "hero.tab2": "老板故事",
    "hero.tab3": "招聘专题",
    "hero.entry1Title": "Boss团队",
    "hero.entry1Copy": "专业招聘顾问团队，人工审核，用心服务每一家企业与每一位人才",
    "hero.entry2Title": "往期访谈",
    "hero.entry2Copy": "走进优秀企业，听老板分享创业故事与用人理念",
    "hero.entry3Title": "人才招聘",
    "hero.entry3Copy": "AI辅助筛选 + 顾问人工匹配，快速找到合适的人才",
    "hero.trust1Title": "信息安全保护",
    "hero.trust1Copy": "企业与人才信息严格保密",
    "hero.trust2Title": "顾问人工审核",
    "hero.trust2Copy": "专业顾问人工确认与跟进",
    "hero.trust3Title": "AI智能辅助",
    "hero.trust3Copy": "简历摘要、人才标签、岗位匹配",
    "hero.trust4Title": "长期合作伙伴",
    "hero.trust4Copy": "服务众多本地优质企业",
    "hero.panelLabel": "我们的服务模式",
    "hero.signal1Title": "AI简历摘要",
    "hero.signal1": "AI自动提取关键信息，生成简历摘要与能力亮点",
    "hero.signal2Title": "人才标签",
    "hero.signal2": "多维度标签体系，精准匹配岗位需求",
    "hero.signal3Title": "顾问审核",
    "hero.signal3": "专业顾问人工审核，深度评估候选人匹配度",
    "hero.signal4Title": "信息保护",
    "hero.signal4": "严格的信息保护机制，保障企业与候选人隐私安全",
    "metrics.talent": "10,000+",
    "metrics.talentLabel": "累计推荐人才",
    "metrics.company": "800+",
    "metrics.companyLabel": "合作企业",
    "metrics.satisfaction": "98%",
    "metrics.satisfactionLabel": "客户满意度",
    "metrics.days": "7天",
    "metrics.daysLabel": "平均推荐周期",
    "trust.oneTitle": "人工审核",
    "trust.oneCopy": "资料由顾问确认后跟进",
    "trust.twoTitle": "信息保护",
    "trust.twoCopy": "不公开完整简历和联系方式",
    "trust.threeTitle": "本地招聘",
    "trust.threeCopy": "聚焦柬埔寨金边及周边需求",
    "trust.fourTitle": "流程清晰",
    "trust.fourCopy": "需求、资料、面试和入职持续跟进",
    "services.eyebrow": "核心服务",
    "services.title": "专业招聘机构级服务，不做开放式简历平台",
    "services.copy": "Boss Hiring 保留人工筛选、人工沟通和人工撮合，以保护企业和候选人信息，并提升招聘成交质量。",
    "services.card1Title": "企业需求收集",
    "services.card1Copy": "收集岗位、人数、薪资、地点、语言、经验和到岗时间。",
    "services.card2Title": "求职资料登记",
    "services.card2Copy": "登记基础资料、工作经验、语言能力、期望岗位和简历。",
    "services.card3Title": "顾问筛选匹配",
    "services.card3Copy": "顾问根据岗位要求和候选人资料进行筛选和推荐。",
    "services.card4Title": "面试入职跟进",
    "services.card4Copy": "协助安排面试、录用沟通、到岗确认和入职反馈。",
    "services.card5Title": "Boss来了内容展示",
    "services.card5Copy": "通过访谈和视频内容帮助企业建立雇主信任。",
    "company.eyebrow": "企业招聘",
    "company.title": "企业招聘，从清晰需求开始",
    "company.copy": "企业提交岗位后，Boss Hiring 顾问会确认岗位细节、候选人条件、福利支持和合作流程，再推进候选人筛选。",
    "company.point1": "确认公司信息、联系人、岗位名称和招聘人数",
    "company.point2": "梳理薪资范围、工作时间、语言和经验要求",
    "company.point3": "确认住宿、签证、工作证等福利支持",
    "company.point4": "提供候选人摘要和匹配说明，保护完整资料",
    "company.cta": "提交企业招聘需求",
    "company.flowTitle": "企业跟进流程",
    "company.step1": "需求提交",
    "company.step2": "顾问联系",
    "company.step3": "岗位确认",
    "company.step4": "筛选候选人",
    "company.step5": "安排面试",
    "company.step6": "入职跟进",
    "candidate.eyebrow": "求职者服务",
    "candidate.title": "登记资料，等待合适机会",
    "candidate.copy": "求职者通过 Telegram 提交个人资料和简历。顾问会审核语言能力、工作经验、期望岗位、薪资预期和可接受工作地点。",
    "candidate.tag1": "中文客服",
    "candidate.tag2": "销售",
    "candidate.tag3": "运营助理",
    "candidate.tag4": "行政人事",
    "candidate.tag5": "金边岗位",
    "candidate.tag6": "可立即入职",
    "candidate.cta": "登记求职资料",
    "team.eyebrow": "Boss Hiring 团队",
    "team.title": "由熟悉本地市场的团队负责筛选与跟进",
    "team.role1": "招聘负责人",
    "team.name1": "招聘顾问负责人",
    "team.copy1": "负责企业需求确认、候选人筛选、面试推进和入职跟进。",
    "team.role2": "企业合作顾问",
    "team.name2": "企业合作顾问",
    "team.copy2": "协助企业梳理岗位要求、薪资范围、福利支持和合作规则。",
    "team.role3": "内容制作",
    "team.name3": "《Boss来了》内容团队",
    "team.copy3": "负责企业访谈、品牌曝光、办公环境展示和招聘内容制作。",
    "show.eyebrow": "Boss来了",
    "show.title": "《Boss来了》让企业被看见，也让人才更放心",
    "show.copy": "通过企业访谈、老板故事、办公环境和岗位介绍，展示柬埔寨本地企业的真实面貌。企业可以申请采访、品牌曝光或招聘合作。",
    "show.cta": "申请企业采访",
    "interviews.eyebrow": "往期访谈",
    "interviews.title": "《Boss来了》往期访谈",
    "interviews.cta": "申请上节目",
    "interviews.play": "播放访谈",
    "interviews.type1": "企业访谈",
    "interviews.video1Title": "本地企业如何找到稳定中文人才",
    "interviews.video1Copy": "围绕企业用人标准、团队文化、岗位要求和候选人沟通方式展开访谈。",
    "interviews.type2": "老板访谈",
    "interviews.video2Title": "金边企业招聘时最看重什么",
    "interviews.video2Copy": "展示老板视角下的岗位能力、语言要求、稳定性和团队管理经验。",
    "interviews.type3": "招聘专题",
    "interviews.video3Title": "求职者如何提高面试通过率",
    "interviews.video3Copy": "分享简历准备、岗位沟通、薪资预期和面试注意事项。",
    "protection.eyebrow": "信息保护",
    "protection.title": "保护信息，保留人工服务的判断力",
    "protection.copy": "Boss Hiring 不让企业直接浏览完整人才库，也不让求职者随意获取全部企业信息。双方资料由顾问整理和筛选后再推进沟通。",
    "protection.card1Title": "对企业",
    "protection.card1Copy": "提供候选人经验摘要、技能标签、期望薪资和匹配说明。",
    "protection.card2Title": "对求职者",
    "protection.card2Copy": "展示岗位类型、薪资范围、工作地点和基础要求。",
    "protection.card3Title": "对团队",
    "protection.card3Copy": "新求职者、新企业需求和合作申请进入内部提醒。",
    "protection.card4Title": "对服务",
    "protection.card4Copy": "保留人工筛选、人工沟通和人工撮合。",
    "contact.eyebrow": "联系",
    "contact.title": "联系 Boss Hiring",
    "contact.copy": "企业招聘、求职登记、《Boss来了》采访和品牌合作，都可以通过 Telegram 联系 Boss Hiring 团队。",
    "contact.company": "企业招聘咨询",
    "contact.candidate": "求职者登记",
    "contact.show": "Boss来了合作申请",
    "contact.telegram": "点击上方按钮进入官方咨询入口",
    "contact.areaLabel": "服务地区：",
    "contact.area": "柬埔寨金边及周边地区",
    "footer.copy": "Boss Hiring 专注柬埔寨招聘服务，连接企业招聘需求、求职者资料登记和《Boss来了》企业内容展示。",
    "footer.services": "服务",
    "footer.company": "公司",
    "footer.contact": "联系",
    "footer.top": "返回顶部",
    "footer.rights": "版权所有。",
    "footer.bottom": "柬埔寨招聘服务。",
  },
  en: {
    "brand.subtitle": "Cambodia Recruitment",
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.employers": "Employers",
    "nav.candidates": "Candidate Service",
    "nav.team": "About Us",
    "nav.interviews": "Interviews",
    "nav.contact": "Contact Us",
    "nav.cta": "Telegram",
    "nav.show": "Boss Show",
    "hero.eyebrow": "Cambodia talent recruitment and enterprise service platform",
    "hero.title": "Boss Show helps companies get seen",
    "hero.copy": "An AI-driven talent recruitment and enterprise service platform connecting hiring, talent screening, and brand exposure.",
    "hero.showCta": "Apply for interview",
    "hero.companyCta": "Post hiring request",
    "hero.candidateCta": "Register as candidate",
    "hero.featureBadge": "Boss Show",
    "hero.featureTitle": "Go inside companies and uncover real growth stories",
    "hero.featureCopy": "We speak with founders, explore industries, and help candidates understand companies while employers build trust.",
    "hero.tab1": "Company interview",
    "hero.tab2": "Founder story",
    "hero.tab3": "Hiring feature",
    "hero.entry1Title": "Boss Team",
    "hero.entry1Copy": "Professional consultants review profiles manually and serve both companies and candidates carefully",
    "hero.entry2Title": "Past Interviews",
    "hero.entry2Copy": "Visit strong companies and hear founders share their stories and hiring views",
    "hero.entry3Title": "Talent Hiring",
    "hero.entry3Copy": "AI-assisted screening plus consultant matching to find suitable talent faster",
    "hero.trust1Title": "Information security",
    "hero.trust1Copy": "Company and candidate data stays protected",
    "hero.trust2Title": "Consultant review",
    "hero.trust2Copy": "Professional consultants verify and follow up",
    "hero.trust3Title": "AI assistance",
    "hero.trust3Copy": "Resume summaries, tags, and role matching",
    "hero.trust4Title": "Long-term partners",
    "hero.trust4Copy": "Serving quality local companies",
    "hero.panelLabel": "Our Service Model",
    "hero.signal1Title": "AI Resume Summary",
    "hero.signal1": "AI extracts key information and generates concise profile highlights",
    "hero.signal2Title": "Talent Tags",
    "hero.signal2": "Multi-dimensional tags help match role requirements accurately",
    "hero.signal3Title": "Consultant Review",
    "hero.signal3": "Professional consultants review and evaluate candidate fit",
    "hero.signal4Title": "Information Protection",
    "hero.signal4": "Strict data protection safeguards companies and candidates",
    "metrics.talent": "10,000+",
    "metrics.talentLabel": "Recommended talents",
    "metrics.company": "800+",
    "metrics.companyLabel": "Partner companies",
    "metrics.satisfaction": "98%",
    "metrics.satisfactionLabel": "Client satisfaction",
    "metrics.days": "7 days",
    "metrics.daysLabel": "Avg. recommendation cycle",
    "trust.oneTitle": "Human Review",
    "trust.oneCopy": "Consultants verify profiles before follow-up",
    "trust.twoTitle": "Data Protection",
    "trust.twoCopy": "Full resumes and contacts are not public",
    "trust.threeTitle": "Local Hiring",
    "trust.threeCopy": "Focused on Phnom Penh and nearby markets",
    "trust.fourTitle": "Clear Process",
    "trust.fourCopy": "Requirements, profiles, interviews, and onboarding are tracked",
    "services.eyebrow": "Core Services",
    "services.title": "Agency-grade recruitment, not an open resume marketplace",
    "services.copy": "Boss Hiring keeps screening, communication, and matching consultant-led to protect both companies and candidates while improving hiring quality.",
    "services.card1Title": "Employer intake",
    "services.card1Copy": "Collect role, headcount, salary, location, language, experience, and start date.",
    "services.card2Title": "Candidate registration",
    "services.card2Copy": "Register profile, experience, languages, expected role, and resume.",
    "services.card3Title": "Consultant matching",
    "services.card3Copy": "Consultants screen and recommend candidates based on role requirements.",
    "services.card4Title": "Interview follow-up",
    "services.card4Copy": "Support interviews, offer communication, arrival confirmation, and onboarding feedback.",
    "services.card5Title": "Boss Show content",
    "services.card5Copy": "Build employer trust through interviews and video content.",
    "company.eyebrow": "For Employers",
    "company.title": "Hiring starts with a clear requirement",
    "company.copy": "After a company submits a role, Boss Hiring consultants confirm role details, candidate requirements, benefits, and cooperation process before screening candidates.",
    "company.point1": "Confirm company info, contact person, role title, and headcount",
    "company.point2": "Clarify salary range, working hours, language, and experience needs",
    "company.point3": "Confirm accommodation, visa, and work permit support",
    "company.point4": "Provide candidate summaries while protecting complete profiles",
    "company.cta": "Submit hiring request",
    "company.flowTitle": "Employer workflow",
    "company.step1": "Request",
    "company.step2": "Consultant call",
    "company.step3": "Role confirmed",
    "company.step4": "Screening",
    "company.step5": "Interview",
    "company.step6": "Onboarding",
    "candidate.eyebrow": "For Candidates",
    "candidate.title": "Register your profile and wait for suitable roles",
    "candidate.copy": "Candidates submit profile and resume via Telegram. Consultants review languages, work experience, expected role, salary, and preferred work location.",
    "candidate.tag1": "Chinese CS",
    "candidate.tag2": "Sales",
    "candidate.tag3": "Operations",
    "candidate.tag4": "HR/Admin",
    "candidate.tag5": "Phnom Penh",
    "candidate.tag6": "Available now",
    "candidate.cta": "Register profile",
    "team.eyebrow": "Boss Hiring Team",
    "team.title": "A local-market team handles screening and follow-up",
    "team.role1": "Recruitment Lead",
    "team.name1": "Recruitment Consultant Lead",
    "team.copy1": "Handles employer requirements, candidate screening, interviews, and onboarding follow-up.",
    "team.role2": "Employer Consultant",
    "team.name2": "Employer Partnership Consultant",
    "team.copy2": "Helps companies clarify role requirements, salary ranges, benefits, and cooperation rules.",
    "team.role3": "Content Producer",
    "team.name3": "Boss Show Content Team",
    "team.copy3": "Produces interviews, employer branding content, office showcases, and hiring stories.",
    "show.eyebrow": "Boss Show",
    "show.title": "Boss Show helps companies be seen and candidates feel confident",
    "show.copy": "Through employer interviews, founder stories, office scenes, and role introductions, Boss Show presents real companies in Cambodia.",
    "show.cta": "Apply for interview",
    "interviews.eyebrow": "Past Interviews",
    "interviews.title": "Boss Show interviews",
    "interviews.cta": "Apply to appear",
    "interviews.play": "Watch interview",
    "interviews.type1": "Employer Interview",
    "interviews.video1Title": "How local companies find stable Chinese-speaking talent",
    "interviews.video1Copy": "A discussion on hiring standards, team culture, role requirements, and candidate communication.",
    "interviews.type2": "Founder Interview",
    "interviews.video2Title": "What Phnom Penh employers value most when hiring",
    "interviews.video2Copy": "A founder perspective on skills, language, stability, and team management.",
    "interviews.type3": "Hiring Topic",
    "interviews.video3Title": "How candidates can improve interview success",
    "interviews.video3Copy": "Resume preparation, role communication, salary expectations, and interview tips.",
    "protection.eyebrow": "Information Protection",
    "protection.title": "Protect information while keeping human judgment",
    "protection.copy": "Boss Hiring does not let employers freely browse the full talent pool or candidates freely access all company details. Consultants organize, screen, and then move communication forward.",
    "protection.card1Title": "For employers",
    "protection.card1Copy": "Candidate summaries, skill tags, expected salary, and match reasons.",
    "protection.card2Title": "For candidates",
    "protection.card2Copy": "Role type, salary range, work location, and basic requirements.",
    "protection.card3Title": "For team",
    "protection.card3Copy": "New candidates, employer requests, and partnership leads trigger internal reminders.",
    "protection.card4Title": "For service",
    "protection.card4Copy": "Screening, communication, and matching remain consultant-led.",
    "contact.eyebrow": "Contact",
    "contact.title": "Contact Boss Hiring",
    "contact.copy": "For hiring, candidate registration, Boss Show interviews, and brand partnerships, contact Boss Hiring via Telegram.",
    "contact.company": "Employer inquiry",
    "contact.candidate": "Candidate registration",
    "contact.show": "Boss Show partnership",
    "contact.telegram": "Use the buttons above to enter the official contact channel",
    "contact.areaLabel": "Service area:",
    "contact.area": "Phnom Penh and nearby areas, Cambodia",
    "footer.copy": "Boss Hiring focuses on recruitment in Cambodia, connecting employer needs, candidate registration, and Boss Show employer content.",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.top": "Back to top",
    "footer.rights": "All rights reserved.",
    "footer.bottom": "Recruitment service in Cambodia.",
  },
  km: {
    "brand.subtitle": "សេវាជ្រើសរើសបុគ្គលិកនៅកម្ពុជា",
    "nav.home": "ទំព័រដើម",
    "nav.services": "សេវាកម្ម",
    "nav.employers": "សម្រាប់ក្រុមហ៊ុន",
    "nav.candidates": "សេវាបេក្ខជន",
    "nav.team": "អំពីយើង",
    "nav.interviews": "បទសម្ភាសន៍",
    "nav.contact": "ទាក់ទងយើង",
    "nav.cta": "Telegram",
    "nav.show": "Boss Show",
    "hero.eyebrow": "វេទិកាជ្រើសរើសបុគ្គលិក និងសេវាក្រុមហ៊ុននៅកម្ពុជា",
    "hero.title": "Boss Show ជួយឱ្យក្រុមហ៊ុនត្រូវបានមើលឃើញ",
    "hero.copy": "វេទិកាជ្រើសរើសបុគ្គលិក និងសេវាក្រុមហ៊ុនដែលជំរុញដោយ AI ភ្ជាប់ការជ្រើសរើស ការត្រួតពិនិត្យបេក្ខជន និងការផ្សព្វផ្សាយម៉ាក។",
    "hero.showCta": "ដាក់ពាក្យសម្ភាសន៍ក្រុមហ៊ុន",
    "hero.companyCta": "ផ្សព្វផ្សាយតម្រូវការជ្រើសរើស",
    "hero.candidateCta": "ចុះឈ្មោះស្វែងរកការងារ",
    "hero.featureBadge": "Boss Show",
    "hero.featureTitle": "ចូលទៅកាន់ខ្សែបន្ទាត់មុខរបស់ក្រុមហ៊ុន និងស្វែងរករឿងរ៉ាវកំណើនពិត",
    "hero.featureCopy": "សន្ទនាជាមួយម្ចាស់ក្រុមហ៊ុន ស្វែងយល់ពីឧស្សាហកម្ម និងជួយឱ្យបេក្ខជនស្គាល់ក្រុមហ៊ុនបានច្បាស់។",
    "hero.tab1": "សម្ភាសន៍ក្រុមហ៊ុន",
    "hero.tab2": "រឿងរ៉ាវម្ចាស់អាជីវកម្ម",
    "hero.tab3": "ប្រធានបទជ្រើសរើស",
    "hero.entry1Title": "ក្រុម Boss",
    "hero.entry1Copy": "ក្រុមទីប្រឹក្សាជំនាញពិនិត្យដោយមនុស្ស និងបម្រើក្រុមហ៊ុននិងបេក្ខជនយ៉ាងយកចិត្តទុកដាក់",
    "hero.entry2Title": "សម្ភាសន៍មុនៗ",
    "hero.entry2Copy": "ចូលទៅកាន់ក្រុមហ៊ុនល្អៗ និងស្តាប់ម្ចាស់ក្រុមហ៊ុនចែករំលែករឿងរ៉ាវ",
    "hero.entry3Title": "ជ្រើសរើសបុគ្គលិក",
    "hero.entry3Copy": "AI ជួយ筛选 និងទីប្រឹក្សាផ្គូផ្គង ដើម្បីរកបុគ្គលិកសមរម្យបានលឿន",
    "hero.trust1Title": "ការពារព័ត៌មាន",
    "hero.trust1Copy": "ព័ត៌មានក្រុមហ៊ុននិងបេក្ខជនត្រូវបានរក្សាសុវត្ថិភាព",
    "hero.trust2Title": "ទីប្រឹក្សាពិនិត្យ",
    "hero.trust2Copy": "ទីប្រឹក្សាជំនាញបញ្ជាក់និងតាមដាន",
    "hero.trust3Title": "AI ជំនួយ",
    "hero.trust3Copy": "សង្ខេបប្រវត្តិរូប ស្លាកបេក្ខជន និងផ្គូផ្គងតួនាទី",
    "hero.trust4Title": "ដៃគូរយៈពេលវែង",
    "hero.trust4Copy": "បម្រើក្រុមហ៊ុនក្នុងស្រុកគុណភាព",
    "hero.panelLabel": "របៀបសេវារបស់យើង",
    "hero.signal1Title": "សង្ខេប CV ដោយ AI",
    "hero.signal1": "AI ដកស្រង់ព័ត៌មានសំខាន់ៗ និងបង្កើតចំណុចលេចធ្លោ",
    "hero.signal2Title": "ស្លាកបេក្ខជន",
    "hero.signal2": "ប្រព័ន្ធស្លាកជាច្រើនមុខ ជួយផ្គូផ្គងតម្រូវការងារ",
    "hero.signal3Title": "ទីប្រឹក្សាពិនិត្យ",
    "hero.signal3": "ទីប្រឹក្សាវិជ្ជាជីវៈពិនិត្យ និងវាយតម្លៃភាពសមស្រប",
    "hero.signal4Title": "ការពារព័ត៌មាន",
    "hero.signal4": "ការពារទិន្នន័យក្រុមហ៊ុន និងបេក្ខជនយ៉ាងតឹងរ៉ឹង",
    "metrics.talent": "10,000+",
    "metrics.talentLabel": "បេក្ខជនដែលបានណែនាំ",
    "metrics.company": "800+",
    "metrics.companyLabel": "ក្រុមហ៊ុនសហការ",
    "metrics.satisfaction": "98%",
    "metrics.satisfactionLabel": "ការពេញចិត្តអតិថិជន",
    "metrics.days": "7 ថ្ងៃ",
    "metrics.daysLabel": "រយៈពេលណែនាំមធ្យម",
    "trust.oneTitle": "ពិនិត្យដោយមនុស្ស",
    "trust.oneCopy": "ទីប្រឹក្សាពិនិត្យមុនពេលតាមដាន",
    "trust.twoTitle": "ការពារព័ត៌មាន",
    "trust.twoCopy": "មិនបង្ហាញ CV និងទំនាក់ទំនងពេញលេញជាសាធារណៈ",
    "trust.threeTitle": "ទីផ្សារកម្ពុជា",
    "trust.threeCopy": "ផ្តោតលើភ្នំពេញ និងតំបន់ជិតខាង",
    "trust.fourTitle": "ដំណើរការច្បាស់លាស់",
    "trust.fourCopy": "តាមដានតម្រូវការ ប្រវត្តិរូប សម្ភាសន៍ និងការចូលធ្វើការ",
    "services.eyebrow": "សេវាសំខាន់ៗ",
    "services.title": "សេវាជ្រើសរើសបែបវិជ្ជាជីវៈ មិនមែនជាវេទិកា CV បើកចំហ",
    "services.copy": "Boss Hiring រក្សាការពិនិត្យ ការទំនាក់ទំនង និងការផ្គូផ្គងដោយទីប្រឹក្សា ដើម្បីការពារក្រុមហ៊ុន និងបេក្ខជន។",
    "services.card1Title": "ប្រមូលតម្រូវការក្រុមហ៊ុន",
    "services.card1Copy": "ប្រមូលមុខតំណែង ចំនួនប្រាក់ខែ ទីតាំង ភាសា បទពិសោធន៍ និងពេលចូលធ្វើការ។",
    "services.card2Title": "ចុះឈ្មោះបេក្ខជន",
    "services.card2Copy": "ចុះឈ្មោះព័ត៌មានមូលដ្ឋាន បទពិសោធន៍ ភាសា មុខតំណែងរំពឹង និង CV។",
    "services.card3Title": "ផ្គូផ្គងដោយទីប្រឹក្សា",
    "services.card3Copy": "ទីប្រឹក្សាពិនិត្យ និងណែនាំបេក្ខជនតាមតម្រូវការការងារ។",
    "services.card4Title": "តាមដានសម្ភាសន៍",
    "services.card4Copy": "ជួយរៀបចំសម្ភាសន៍ ការទទួលចូលធ្វើការ និងមតិត្រឡប់។",
    "services.card5Title": "មាតិកា Boss Show",
    "services.card5Copy": "បង្កើនទំនុកចិត្តក្រុមហ៊ុនតាមរយៈវីដេអូ និងបទសម្ភាសន៍។",
    "company.eyebrow": "សម្រាប់ក្រុមហ៊ុន",
    "company.title": "ការជ្រើសរើសចាប់ផ្តើមពីតម្រូវការច្បាស់លាស់",
    "company.copy": "បន្ទាប់ពីក្រុមហ៊ុនដាក់មុខតំណែង ទីប្រឹក្សា Boss Hiring នឹងបញ្ជាក់ព័ត៌មានការងារ លក្ខខណ្ឌបេក្ខជន អត្ថប្រយោជន៍ និងដំណើរការសហការ។",
    "company.point1": "បញ្ជាក់ព័ត៌មានក្រុមហ៊ុន អ្នកទំនាក់ទំនង មុខតំណែង និងចំនួនត្រូវការ",
    "company.point2": "បញ្ជាក់ប្រាក់ខែ ម៉ោងធ្វើការ ភាសា និងបទពិសោធន៍",
    "company.point3": "បញ្ជាក់ការស្នាក់នៅ វីសា និងលិខិតការងារ",
    "company.point4": "ផ្តល់សង្ខេបបេក្ខជន និងការពារព័ត៌មានពេញលេញ",
    "company.cta": "ដាក់តម្រូវការជ្រើសរើស",
    "company.flowTitle": "ដំណើរការសម្រាប់ក្រុមហ៊ុន",
    "company.step1": "ដាក់តម្រូវការ",
    "company.step2": "ទីប្រឹក្សាទាក់ទង",
    "company.step3": "បញ្ជាក់មុខតំណែង",
    "company.step4": "ពិនិត្យបេក្ខជន",
    "company.step5": "សម្ភាសន៍",
    "company.step6": "ចូលធ្វើការ",
    "candidate.eyebrow": "សម្រាប់បេក្ខជន",
    "candidate.title": "ចុះឈ្មោះព័ត៌មាន ហើយរង់ចាំឱកាសសមរម្យ",
    "candidate.copy": "បេក្ខជនដាក់ព័ត៌មាន និង CV តាម Telegram។ ទីប្រឹក្សាពិនិត្យភាសា បទពិសោធន៍ មុខតំណែងរំពឹង ប្រាក់ខែ និងទីតាំងធ្វើការ។",
    "candidate.tag1": "សេវាអតិថិជនចិន",
    "candidate.tag2": "លក់",
    "candidate.tag3": "ប្រតិបត្តិការ",
    "candidate.tag4": "រដ្ឋបាល/HR",
    "candidate.tag5": "ភ្នំពេញ",
    "candidate.tag6": "ចូលធ្វើការបានភ្លាម",
    "candidate.cta": "ចុះឈ្មោះបេក្ខជន",
    "team.eyebrow": "ក្រុម Boss Hiring",
    "team.title": "ក្រុមដែលយល់ទីផ្សារកម្ពុជា ជួយពិនិត្យ និងតាមដាន",
    "team.role1": "ប្រធានជ្រើសរើស",
    "team.name1": "ប្រធានទីប្រឹក្សាជ្រើសរើស",
    "team.copy1": "ទទួលខុសត្រូវលើតម្រូវការក្រុមហ៊ុន ពិនិត្យបេក្ខជន សម្ភាសន៍ និងតាមដាន។",
    "team.role2": "ទីប្រឹក្សាក្រុមហ៊ុន",
    "team.name2": "ទីប្រឹក្សាសហការក្រុមហ៊ុន",
    "team.copy2": "ជួយក្រុមហ៊ុនកំណត់លក្ខខណ្ឌការងារ ប្រាក់ខែ អត្ថប្រយោជន៍ និងច្បាប់សហការ។",
    "team.role3": "ផលិតមាតិកា",
    "team.name3": "ក្រុមមាតិកា Boss Show",
    "team.copy3": "ផលិតបទសម្ភាសន៍ ការផ្សព្វផ្សាយម៉ាក ការបង្ហាញការិយាល័យ និងរឿងរ៉ាវជ្រើសរើស។",
    "show.eyebrow": "Boss Show",
    "show.title": "Boss Show ធ្វើឱ្យក្រុមហ៊ុនត្រូវបានមើលឃើញ និងបេក្ខជនមានទំនុកចិត្ត",
    "show.copy": "តាមរយៈបទសម្ភាសន៍ រឿងរ៉ាវម្ចាស់ក្រុមហ៊ុន បរិយាកាសការិយាល័យ និងការណែនាំមុខតំណែង Boss Show បង្ហាញក្រុមហ៊ុនពិតនៅកម្ពុជា។",
    "show.cta": "ស្នើសុំសម្ភាសន៍",
    "interviews.eyebrow": "បទសម្ភាសន៍មុនៗ",
    "interviews.title": "បទសម្ភាសន៍ Boss Show",
    "interviews.cta": "ស្នើចូលកម្មវិធី",
    "interviews.play": "មើលបទសម្ភាសន៍",
    "interviews.type1": "បទសម្ភាសន៍ក្រុមហ៊ុន",
    "interviews.video1Title": "ក្រុមហ៊ុនក្នុងស្រុករកបុគ្គលិកនិយាយចិនដែលមានស្ថេរភាពយ៉ាងដូចម្តេច",
    "interviews.video1Copy": "ពិភាក្សាអំពីស្តង់ដារជ្រើសរើស វប្បធម៌ក្រុម តម្រូវការមុខតំណែង និងការទំនាក់ទំនងបេក្ខជន។",
    "interviews.type2": "បទសម្ភាសន៍ម្ចាស់ក្រុមហ៊ុន",
    "interviews.video2Title": "និយោជកនៅភ្នំពេញមើលអ្វីសំខាន់បំផុតពេលជ្រើសរើស",
    "interviews.video2Copy": "មើលពីទស្សនៈម្ចាស់ក្រុមហ៊ុនលើជំនាញ ភាសា ស្ថេរភាព និងការគ្រប់គ្រងក្រុម។",
    "interviews.type3": "ប្រធានបទការងារ",
    "interviews.video3Title": "បេក្ខជនបង្កើនឱកាសជាប់សម្ភាសន៍បានយ៉ាងដូចម្តេច",
    "interviews.video3Copy": "ការរៀបចំ CV ការទំនាក់ទំនងមុខតំណែង ការរំពឹងប្រាក់ខែ និងគន្លឹះសម្ភាសន៍។",
    "protection.eyebrow": "ការពារព័ត៌មាន",
    "protection.title": "ការពារព័ត៌មាន និងរក្សាការវិនិច្ឆ័យដោយមនុស្ស",
    "protection.copy": "Boss Hiring មិនអនុញ្ញាតឱ្យក្រុមហ៊ុនមើលបេក្ខជនទាំងអស់ដោយសេរី ឬឱ្យបេក្ខជនទទួលព័ត៌មានក្រុមហ៊ុនទាំងអស់ដោយសេរីទេ។ ទីប្រឹក្សារៀបចំ ពិនិត្យ ហើយបន្តការទំនាក់ទំនង។",
    "protection.card1Title": "សម្រាប់ក្រុមហ៊ុន",
    "protection.card1Copy": "ផ្តល់សង្ខេបបទពិសោធន៍ ស្លាកជំនាញ ប្រាក់ខែរំពឹង និងហេតុផលផ្គូផ្គង។",
    "protection.card2Title": "សម្រាប់បេក្ខជន",
    "protection.card2Copy": "បង្ហាញប្រភេទការងារ ប្រាក់ខែ ទីតាំង និងលក្ខខណ្ឌមូលដ្ឋាន។",
    "protection.card3Title": "សម្រាប់ក្រុម",
    "protection.card3Copy": "បេក្ខជនថ្មី តម្រូវការក្រុមហ៊ុន និងសំណើសហការនឹងមានការជូនដំណឹងក្នុងក្រុម។",
    "protection.card4Title": "សម្រាប់សេវា",
    "protection.card4Copy": "ការពិនិត្យ ការទំនាក់ទំនង និងការផ្គូផ្គងធ្វើដោយទីប្រឹក្សា។",
    "contact.eyebrow": "ទំនាក់ទំនង",
    "contact.title": "ទាក់ទង Boss Hiring",
    "contact.copy": "សម្រាប់ការជ្រើសរើស ការចុះឈ្មោះបេក្ខជន បទសម្ភាសន៍ Boss Show និងសហការម៉ាក សូមទាក់ទង Boss Hiring តាម Telegram។",
    "contact.company": "ពិគ្រោះសម្រាប់ក្រុមហ៊ុន",
    "contact.candidate": "ចុះឈ្មោះបេក្ខជន",
    "contact.show": "សហការ Boss Show",
    "contact.telegram": "ចុចប៊ូតុងខាងលើដើម្បីចូលช่องទំនាក់ទំនងផ្លូវការ",
    "contact.areaLabel": "តំបន់សេវា៖",
    "contact.area": "ភ្នំពេញ និងតំបន់ជិតខាង កម្ពុជា",
    "footer.copy": "Boss Hiring ផ្តោតលើសេវាជ្រើសរើសនៅកម្ពុជា ដោយភ្ជាប់តម្រូវការក្រុមហ៊ុន ការចុះឈ្មោះបេក្ខជន និងមាតិកា Boss Show។",
    "footer.services": "សេវាកម្ម",
    "footer.company": "ក្រុមហ៊ុន",
    "footer.contact": "ទំនាក់ទំនង",
    "footer.top": "ត្រឡប់ទៅលើ",
    "footer.rights": "រក្សាសិទ្ធិគ្រប់យ៉ាង។",
    "footer.bottom": "សេវាជ្រើសរើសបុគ្គលិកនៅកម្ពុជា។",
  },
};

function setLanguage(lang) {
  const messages = I18N[lang] || I18N.zh;
  document.documentElement.lang = lang === "km" ? "km" : lang === "en" ? "en" : "zh-CN";
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (messages[key]) {
      node.textContent = messages[key];
    }
  });
  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("is-active", button.getAttribute("data-lang") === lang);
  });
  localStorage.setItem("bossHiringLang", lang);
}

const header = document.querySelector("[data-header]");
const menuButton = document.querySelector("[data-menu-button]");

if (menuButton && header) {
  menuButton.addEventListener("click", () => {
    header.classList.toggle("is-open");
  });
}

document.querySelectorAll("[data-nav] a").forEach((link) => {
  link.addEventListener("click", () => {
    header?.classList.remove("is-open");
  });
});

document.querySelectorAll("[data-telegram]").forEach((link) => {
  const key = link.getAttribute("data-telegram");
  const suffix = SITE_CONFIG.telegramStarts[key] || "";
  link.href = `${SITE_CONFIG.telegramBaseUrl}${suffix}`;
});

document.querySelectorAll("[data-email]").forEach((link) => {
  link.href = `mailto:${SITE_CONFIG.email}`;
  link.textContent = SITE_CONFIG.email;
});

document.querySelectorAll("[data-social]").forEach((link) => {
  const key = link.getAttribute("data-social");
  link.href = SITE_CONFIG.socialLinks[key] || "#";
});

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => {
    setLanguage(button.getAttribute("data-lang") || "zh");
  });
});

setLanguage(localStorage.getItem("bossHiringLang") || "zh");

const year = document.querySelector("[data-year]");
if (year) {
  year.textContent = new Date().getFullYear();
}

document.querySelectorAll("[data-count]").forEach((item) => {
  const target = Number(item.getAttribute("data-count") || "0");
  const duration = 1100;
  const start = performance.now();

  const tick = (now) => {
    const progress = Math.min((now - start) / duration, 1);
    item.textContent = String(Math.round(target * progress));
    if (progress < 1) {
      requestAnimationFrame(tick);
    }
  };

  requestAnimationFrame(tick);
});

const filterButtons = document.querySelectorAll("[data-filter]");
const jobCards = document.querySelectorAll("[data-job-category]");
const jobSearch = document.querySelector("[data-job-search]");

filterButtons.forEach((button) => {
  button.addEventListener("click", () => {
    const selected = button.getAttribute("data-filter");

    filterButtons.forEach((item) => item.classList.remove("is-active"));
    button.classList.add("is-active");

    jobCards.forEach((card) => {
      const category = card.getAttribute("data-job-category");
      card.classList.toggle("is-hidden", selected !== "all" && selected !== category);
    });
  });
});

if (jobSearch) {
  jobSearch.addEventListener("input", () => {
    const term = jobSearch.value.trim().toLowerCase();
    jobCards.forEach((card) => {
      const text = card.getAttribute("data-search-text")?.toLowerCase() || card.textContent.toLowerCase();
      card.classList.toggle("is-hidden", term.length > 0 && !text.includes(term));
    });
  });
}

document.querySelectorAll("[data-admin-link]").forEach((link) => {
  link.href = SITE_CONFIG.adminUrl;
});
